//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abc.Test.Services.Client.Datum.Client {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Secured", Namespace="http://schemas.datacontract.org/2004/07/Abc.Services.Contracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Abc.Test.Services.Client.Datum.Client.ServerStatisticSet))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Abc.Test.Services.Client.Datum.Client.Configuration))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Abc.Test.Services.Client.Datum.Client.LogItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Abc.Test.Services.Client.Datum.Client.Message))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Abc.Test.Services.Client.Datum.Client.Occurrence))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Abc.Test.Services.Client.Datum.Client.EventLogItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Abc.Test.Services.Client.Datum.Client.ErrorItem))]
    public partial class Secured : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Abc.Test.Services.Client.Datum.Client.Token TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Abc.Test.Services.Client.Datum.Client.Token Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Token", Namespace="http://schemas.datacontract.org/2004/07/Abc.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class Token : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ApplicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValidationKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                if ((this.ApplicationIdField.Equals(value) != true)) {
                    this.ApplicationIdField = value;
                    this.RaisePropertyChanged("ApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValidationKey {
            get {
                return this.ValidationKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidationKeyField, value) != true)) {
                    this.ValidationKeyField = value;
                    this.RaisePropertyChanged("ValidationKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerStatisticSet", Namespace="http://schemas.datacontract.org/2004/07/Abc.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ServerStatisticSet : Abc.Test.Services.Client.Datum.Client.Secured {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float CpuUsagePercentageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeploymentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MachineNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float MemoryUsagePercentageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float[] NetworkPercentagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OccurredOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PhysicalDiskUsagePercentageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float CpuUsagePercentage {
            get {
                return this.CpuUsagePercentageField;
            }
            set {
                if ((this.CpuUsagePercentageField.Equals(value) != true)) {
                    this.CpuUsagePercentageField = value;
                    this.RaisePropertyChanged("CpuUsagePercentage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeploymentId {
            get {
                return this.DeploymentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DeploymentIdField, value) != true)) {
                    this.DeploymentIdField = value;
                    this.RaisePropertyChanged("DeploymentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MachineName {
            get {
                return this.MachineNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MachineNameField, value) != true)) {
                    this.MachineNameField = value;
                    this.RaisePropertyChanged("MachineName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float MemoryUsagePercentage {
            get {
                return this.MemoryUsagePercentageField;
            }
            set {
                if ((this.MemoryUsagePercentageField.Equals(value) != true)) {
                    this.MemoryUsagePercentageField = value;
                    this.RaisePropertyChanged("MemoryUsagePercentage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float[] NetworkPercentages {
            get {
                return this.NetworkPercentagesField;
            }
            set {
                if ((object.ReferenceEquals(this.NetworkPercentagesField, value) != true)) {
                    this.NetworkPercentagesField = value;
                    this.RaisePropertyChanged("NetworkPercentages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OccurredOn {
            get {
                return this.OccurredOnField;
            }
            set {
                if ((this.OccurredOnField.Equals(value) != true)) {
                    this.OccurredOnField = value;
                    this.RaisePropertyChanged("OccurredOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float PhysicalDiskUsagePercentage {
            get {
                return this.PhysicalDiskUsagePercentageField;
            }
            set {
                if ((this.PhysicalDiskUsagePercentageField.Equals(value) != true)) {
                    this.PhysicalDiskUsagePercentageField = value;
                    this.RaisePropertyChanged("PhysicalDiskUsagePercentage");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Configuration", Namespace="http://schemas.datacontract.org/2004/07/Abc.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class Configuration : Abc.Test.Services.Client.Datum.Client.Secured {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogItem", Namespace="http://schemas.datacontract.org/2004/07/Abc.Services.Contracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Abc.Test.Services.Client.Datum.Client.Message))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Abc.Test.Services.Client.Datum.Client.Occurrence))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Abc.Test.Services.Client.Datum.Client.EventLogItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Abc.Test.Services.Client.Datum.Client.ErrorItem))]
    public partial class LogItem : Abc.Test.Services.Client.Datum.Client.Secured {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeploymentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MachineNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OccurredOnField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeploymentId {
            get {
                return this.DeploymentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DeploymentIdField, value) != true)) {
                    this.DeploymentIdField = value;
                    this.RaisePropertyChanged("DeploymentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MachineName {
            get {
                return this.MachineNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MachineNameField, value) != true)) {
                    this.MachineNameField = value;
                    this.RaisePropertyChanged("MachineName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OccurredOn {
            get {
                return this.OccurredOnField;
            }
            set {
                if ((this.OccurredOnField.Equals(value) != true)) {
                    this.OccurredOnField = value;
                    this.RaisePropertyChanged("OccurredOn");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/Abc.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class Message : Abc.Test.Services.Client.Datum.Client.LogItem {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> SessionIdentifierField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> SessionIdentifier {
            get {
                return this.SessionIdentifierField;
            }
            set {
                if ((this.SessionIdentifierField.Equals(value) != true)) {
                    this.SessionIdentifierField = value;
                    this.RaisePropertyChanged("SessionIdentifier");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Occurrence", Namespace="http://schemas.datacontract.org/2004/07/Abc.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class Occurrence : Abc.Test.Services.Client.Datum.Client.LogItem {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> SessionIdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ThreadIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Class {
            get {
                return this.ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassField, value) != true)) {
                    this.ClassField = value;
                    this.RaisePropertyChanged("Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Method {
            get {
                return this.MethodField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodField, value) != true)) {
                    this.MethodField = value;
                    this.RaisePropertyChanged("Method");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> SessionIdentifier {
            get {
                return this.SessionIdentifierField;
            }
            set {
                if ((this.SessionIdentifierField.Equals(value) != true)) {
                    this.SessionIdentifierField = value;
                    this.RaisePropertyChanged("SessionIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ThreadId {
            get {
                return this.ThreadIdField;
            }
            set {
                if ((this.ThreadIdField.Equals(value) != true)) {
                    this.ThreadIdField = value;
                    this.RaisePropertyChanged("ThreadId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventLogItem", Namespace="http://schemas.datacontract.org/2004/07/Abc.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class EventLogItem : Abc.Test.Services.Client.Datum.Client.LogItem {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Abc.Test.Services.Client.Datum.Client.EventLogEntryType EntryTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EventIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long InstanceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Abc.Test.Services.Client.Datum.Client.EventLogEntryType EntryType {
            get {
                return this.EntryTypeField;
            }
            set {
                if ((this.EntryTypeField.Equals(value) != true)) {
                    this.EntryTypeField = value;
                    this.RaisePropertyChanged("EntryType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((this.EventIdField.Equals(value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long InstanceId {
            get {
                return this.InstanceIdField;
            }
            set {
                if ((this.InstanceIdField.Equals(value) != true)) {
                    this.InstanceIdField = value;
                    this.RaisePropertyChanged("InstanceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorItem", Namespace="http://schemas.datacontract.org/2004/07/Abc.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ErrorItem : Abc.Test.Services.Client.Datum.Client.LogItem {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Abc.Test.Services.Client.Datum.Client.EventTypes EventTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Abc.Test.Services.Client.Datum.Client.ErrorItem ParentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> SessionIdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClassName {
            get {
                return this.ClassNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassNameField, value) != true)) {
                    this.ClassNameField = value;
                    this.RaisePropertyChanged("ClassName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Abc.Test.Services.Client.Datum.Client.EventTypes EventType {
            get {
                return this.EventTypeField;
            }
            set {
                if ((this.EventTypeField.Equals(value) != true)) {
                    this.EventTypeField = value;
                    this.RaisePropertyChanged("EventType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Abc.Test.Services.Client.Datum.Client.ErrorItem Parent {
            get {
                return this.ParentField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentField, value) != true)) {
                    this.ParentField = value;
                    this.RaisePropertyChanged("Parent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> SessionIdentifier {
            get {
                return this.SessionIdentifierField;
            }
            set {
                if ((this.SessionIdentifierField.Equals(value) != true)) {
                    this.SessionIdentifierField = value;
                    this.RaisePropertyChanged("SessionIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventTypes", Namespace="http://schemas.datacontract.org/2004/07/Abc.Services.Contracts")]
    public enum EventTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Critical = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Information = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Verbose = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Start = 256,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Stop = 512,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Suspend = 1024,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Resume = 2048,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Transfer = 4096,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventLogEntryType", Namespace="http://schemas.datacontract.org/2004/07/Abc.Services.Contracts")]
    public enum EventLogEntryType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Information = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SuccessAudit = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailureAudit = 16,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Datum.Client.IDatum")]
    public interface IDatum {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatum/LogException", ReplyAction="http://tempuri.org/IDatum/LogExceptionResponse")]
        void LogException(Abc.Test.Services.Client.Datum.Client.ErrorItem exception);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatum/LogMessage", ReplyAction="http://tempuri.org/IDatum/LogMessageResponse")]
        void LogMessage(Abc.Test.Services.Client.Datum.Client.Message message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatum/LogServerStatisticSet", ReplyAction="http://tempuri.org/IDatum/LogServerStatisticSetResponse")]
        void LogServerStatisticSet(Abc.Test.Services.Client.Datum.Client.ServerStatisticSet data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatum/LogPerformance", ReplyAction="http://tempuri.org/IDatum/LogPerformanceResponse")]
        void LogPerformance(Abc.Test.Services.Client.Datum.Client.Occurrence occurrence);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatum/LogEventItem", ReplyAction="http://tempuri.org/IDatum/LogEventItemResponse")]
        void LogEventItem(Abc.Test.Services.Client.Datum.Client.EventLogItem item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDatum/GetConfiguration", ReplyAction="http://tempuri.org/IDatum/GetConfigurationResponse")]
        Abc.Test.Services.Client.Datum.Client.Configuration[] GetConfiguration(Abc.Test.Services.Client.Datum.Client.Configuration configuration);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDatumChannel : Abc.Test.Services.Client.Datum.Client.IDatum, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DatumClient : System.ServiceModel.ClientBase<Abc.Test.Services.Client.Datum.Client.IDatum>, Abc.Test.Services.Client.Datum.Client.IDatum {
        
        public DatumClient() {
        }
        
        public DatumClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DatumClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatumClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatumClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void LogException(Abc.Test.Services.Client.Datum.Client.ErrorItem exception) {
            base.Channel.LogException(exception);
        }
        
        public void LogMessage(Abc.Test.Services.Client.Datum.Client.Message message) {
            base.Channel.LogMessage(message);
        }
        
        public void LogServerStatisticSet(Abc.Test.Services.Client.Datum.Client.ServerStatisticSet data) {
            base.Channel.LogServerStatisticSet(data);
        }
        
        public void LogPerformance(Abc.Test.Services.Client.Datum.Client.Occurrence occurrence) {
            base.Channel.LogPerformance(occurrence);
        }
        
        public void LogEventItem(Abc.Test.Services.Client.Datum.Client.EventLogItem item) {
            base.Channel.LogEventItem(item);
        }
        
        public Abc.Test.Services.Client.Datum.Client.Configuration[] GetConfiguration(Abc.Test.Services.Client.Datum.Client.Configuration configuration) {
            return base.Channel.GetConfiguration(configuration);
        }
    }
}
